using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Wilberforce;

public class ChangeColorblindMode : MonoBehaviour
{
	public Colorblind cbScript;
	public int u;
	
	void Start()
	{
		cbScript.Type = PlayerPrefs.GetInt("colorblind");
	}
	
    void Update()
    {
        u = cbScript.Type;
    }
	
	//Normal Vision = 0
	//Protanopia = 1
	//Deuteranopia = 2
	//Tritanopia = 3
	
	public void DisableColorblindMode()
	{
		cbScript.Type = 0;
		PlayerPrefs.SetInt("colorblind", cbScript.Type);
	}
	public void EnableProtanopia()
	{
		cbScript.Type = 1;
		PlayerPrefs.SetInt("colorblind", cbScript.Type);
	}
	public void EnableDeuteranopia()
	{
		cbScript.Type = 2;
		PlayerPrefs.SetInt("colorblind", cbScript.Type);
	}
	public void EnableTritanopia()
	{
		cbScript.Type = 3;
		PlayerPrefs.SetInt("colorblind", cbScript.Type);
	}
}
